// stenciljs/src/components/custom-dialog/custom-dialog.tsx
import { Component, Host, h } from '@stencil/core';
import { getBundles } from '@genexus/mercury';

import { getIconPath } from '@genexus/mercury';
const bundles = getBundles(['components/button', 'components/icon'], '/assets/css/');

const ICON = getIconPath({
  category: 'system',
  name: 'add-circle',
  colorType: 'primary',
});
@Component({
  shadow: true,
  styleUrl: 'custom-dialog.css',
  tag: 'custom-dialog',
})
export class CustomDialog {
  render() {
    return (
      <Host>
        <ch-theme model={bundles}></ch-theme>
        <button class="button-primary button-icon-and-text" type="button">
          <ch-image class="icon-md" src={ICON} type="mask" />
          Caption
        </button>
      </Host>
    );
  }
}

// angular-ssr/src/app/custom-dialog/custom-dialog.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';

import { getBundles } from '@genexus/mercury/bundles.js';
import { getIconPath } from '@genexus/mercury/assets-manager.js';

@Component({
  selector: 'custom-dialog',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `<ch-theme [model]="bundles"></ch-theme>
    <button class="button-primary button-icon-and-text" type="button">
      <ch-image class="icon-md" [src]="ICON" [type]="'mask'" />
      Caption
    </button>`,
})
export class CustomDialogComponent {
  bundles = getBundles(
    ['components/button', 'components/icon'],
    '/assets/css/',
  );
  ICON = getIconPath({
    category: 'system',
    name: 'add-circle',
    colorType: 'primary',
  });
}
